name: Compile LaTeX to HTML

on:
  push:
    paths:
      - '*.tex'
      - '.github/workflows/latex_2_html.yml'
      - '*.css'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - # ... (Your previous steps remain unchanged)

    - name: Install TeX Live, latex2html, and other required packages
      run: sudo apt-get install -y texlive texlive-latex-extra texlive-bibtex-extra biber latex2html

    - name: Compile LaTeX with references and glossary
      run: |
        pdflatex 00_main.tex
        bibtex 00_main
        makeglossaries 00_main
        pdflatex 00_main.tex
        pdflatex 00_main.tex

    - name: Convert PDF to HTML
      run: |
        latex2html -dir docs -mkdir 00_main.tex

    # - name: Add custom styling
    #   run: |
    #     cp custom_styles.css docs/
    #     echo '<link rel="stylesheet" type="text/css" href="custom_styles.css">' >> docs/00_main.html

    - name: Commit and Push to Repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/*
        git commit -m "Add generated HTML page" || exit 0
        git push origin || exit 0
